apiVersion: v1
kind: Service
metadata:
  name: {{ include "capk.name" . }}
  labels:
    app: {{ include "capk.name" . }}
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 4004
  selector:
    app: {{ include "capk.name" . }}


